name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # This step checks out the repo, which is generally required

      - uses: athul/waka-readme@v2.0.0 # Change this to the latest version
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          # meta
          API_BASE_URL: https://wakatime.com/api
          # content
          SHOW_TITLE: true
          SECTION_NAME: waka
          BLOCKS: "░▒▓█"
          CODE_LANG: all_time 
          TIME_RANGE: last_7_days # Modify as per your needs
          LANG_COUNT: 10
          SHOW_TIME: true
          SHOW_TOTAL: true
          SHOW_MASKED_TIME: false
          STOP_AT_OTHER: true
          # commit
          COMMIT_MESSAGE: Updated waka-readme graph with new metrics
          TARGET_BRANCH: main # Change to main if your default branch is main
          TARGET_PATH: README.md
          COMMITTER_NAME: GitHubActionBot
          COMMITTER_EMAIL: action-bot@example.com # Use a valid placeholder email
          AUTHOR_NAME: Athul
